### PR TITLE
Fix typo in Project.toml: julia compat

### PR DESCRIPTION
**Pull request by NHDaly**
Oops: dependency version requirements go in the `[compat]` section!

This fixes the typo introduced in #6. Sorry about that!

### CODE REVIEW

**Comment by NHDaly** [comment]
i'm testing this now at:
https://mybinder.org/v2/gh/NHDaly/multi-language-demo/patch-1

I'll let you know if it succeeds

**Comment by NHDaly** [comment]
Drats: Yeah, i was worried it wouldn't be this easy..

@betatim -- the Julia notebook now works just fine. :) So that's great! 👌

However, the `23-Cross-Language-Integration.ipynb` notebook, the star of the show, failed when importing the Julia magic, but I've fixed it in the latest commit.

This is the failure:

```
%load_ext julia.magic
```
```
RuntimeError: It seems your Julia and PyJulia setup are not supported.

Julia executable:
    julia
Python interpreter and libpython used by PyCall.jl:
    /srv/conda/envs/notebook/bin/python3
    /srv/conda/envs/notebook/lib/libpython3.7m.so.1.0
Python interpreter used to import PyJulia and its libpython.
    /srv/conda/envs/notebook/bin/python
    /srv/conda/envs/notebook/lib/libpython3.7m.a

Your Python interpreter "/srv/conda/envs/notebook/bin/python"
is statically linked to libpython.  Currently, PyJulia does not fully
support such Python interpreter.

The easiest workaround is to pass `compiled_modules=False` to `Julia`
constructor.  To do so, first *reboot* your Python REPL (if this happened
inside an interactive session) and then evaluate:

    >>> from julia.api import Julia
    >>> jl = Julia(compiled_modules=False)

Another workaround is to run your Python script with `python-jl`
command bundled in PyJulia.  You can simply do:

    $ python-jl PATH/TO/YOUR/SCRIPT.py

See `python-jl --help` for more information.

For more information, see:

    https://pyjulia.readthedocs.io/en/latest/troubleshooting.html

```

I've followed the instructions there, and fixed it by adding this block as cell `42`:
```python
from julia.api import Julia
jl = Julia(compiled_modules=False)
```

(Also, of note, i couldn't get the Fortran parts to run, even on Binder. I don't know if I broke that? But so anyway I just manually merged the cells from my .ipynb json over to this repo. it seems to have merged cleanly! 😊It might be worth getting @Carreau's 👀 on this as well? Though note that because of #6, this repo now does not build at all.)

**Comment by betatim** [comment]
Let's give @Carreau a chance to see and think about this. I don't really know much about how to fix up all of these things either.

Maybe we should make a travis snippet that:
1. installs repo2docker from `master` and
2. runs `repo2docker . ./verify` (a short bash script called `verify` that runs the notebooks it can find in a repo)

to help us figure out if things are broken or not :)

**Comment by NHDaly** [comment]
Yeah having some Travis CI sounds like a good idea!

But yeah, as far as I can tell, I THINK I've fixed all the issues I
introduced now. :)

**Review by betatim — APPROVED** [review]
Ping me if there is no activity in the next 48h, then we can merge this and fix things later.

**Pull request merged**
