### PR TITLE
Removed axes() because not defined

### PR DESCRIPTION
**Pull request by hdrake**
I got the following error when I tried to run this notebook through binder. Not very experienced with Julia so sure what the problem is...
'''
UndefVarError: axes not defined

Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:522
 [2] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /srv/julia/pkg/v0.6/IJulia/src/execute_request.jl:193
 [3] (::Compat.#inner#6{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /srv/julia/pkg/v0.6/Compat/src/Compat.jl:125
 [4] eventloop(::ZMQ.Socket) at /srv/julia/pkg/v0.6/IJulia/src/eventloop.jl:8
 [5] (::IJulia.##13#16)() at ./task.jl:335
'''

I removed `ax = axes()` and it runs fine since `ax` variable is never called anyways.

### CODE REVIEW

**Comment by betatim** [comment]
Merged. I also don't remember why it is here. Let's see if someone comes to explain to us why it is needed :)

Thanks for taking the time to fix things up!

**Comment by betatim** [comment]
Maybe @NHDaly knows?

**Comment by NHDaly** [comment]
Huh, yeah, looking through the commit history on `PyPlot.jl`, it looks like they stopped exporting the `axes()` function into the user's namespace in the last release that still supported Julia 0.6:
https://github.com/JuliaPy/PyPlot.jl/commit/c7afdfd64539ff411df565d8b74ed63fcf6aee86

You can still access it through `PyPlot.axes()`, if you need to, but I think removing it as you've done here seems fine as well. :) Thanks for the PR! :)


More generally, though, @betatim, we should _definitely_ update this file to be a Julia 1.0 notebook, as Julia 0.6 is not a supported release.

**Comment by NHDaly** [comment]
I've opened https://github.com/binder-examples/multi-language-demo/pull/6 to update it. :)

(To clarify, one of the main reasons it's worth updating is that in Julia 1.0 we start supporting the Manifest.toml, so after PR #6, we will have a hard-coded version of PyPlot, so that the code will never break in the (foreseeable) future because it will always install the same version of julia and its package dependencies.)

**Comment by NHDaly** [comment]
(To clarify, one of the main reasons it's worth updating is that in Julia 1.0 we start supporting the Manifest.toml, so after PR #6, we will have a hard-coded version of PyPlot, so that the code will never break in the (foreseeable) future because it will always install the same version of julia and its package dependencies.)

**Pull request merged**
