### PR TITLE
Add IRKernel to the mix

### PR DESCRIPTION
**Pull request by betatim**
Is there a good notebook we can use to demonstrate "just R"?

### CODE REVIEW

**Comment by choldgraf** [comment]
so the trick here is that I *think* repo2docker actually won't compose these environments. If we give an R environment it'll overload the Python one (or vice versa)

**Comment by betatim** [comment]
Correct.

I thought I could be clever and call `Rscript install.R` from `postBuild`. Running that command in a terminal once the binder is up and running does seem to get me an IRKernel. But it seems when `postBuild` is executed something is configured slightly differently :-/

This was in response to https://github.com/jupyterhub/binder/issues/107 so maybe @sdwfrost wants to take this over as it is nearly working but not quite.

**Comment by larssp** [comment]
installing R packages from a Jupyter Terminal session leads to 
`'lib = "/usr/local/lib/R/site-library"' is not writable`

Creating a package dir in the home directory via postBuild, installing required packages with the `lib` flag and running 
`IRkernel::installspec(user=TRUE,rprofile="~/binder/.Rprofile")` does the trick.
The .Rprofile makes sure that the R kernel can find the packages.

[This repo](https://github.com/larssp/mybinder-J-Py-R-oct) solves jupyterhub/binder#107

**Comment by choldgraf** [comment]
@betatim what's the state of this PR?

**Comment by betatim** [comment]
I think the issue is solved via the comments/links in https://github.com/binder-examples/multi-language-demo/pull/1#issuecomment-417584848

This PR never actually worked and there is no need to figure out why. At least from my side.

**Pull request closed without merging**
